### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mull**
Test suite still works, haven't tried to use it in a project yet. Thought I'd send the PR for convenience!

### CODE REVIEW

**Comment by badosu** [comment]
Can you update to Sequel > 4, Sequel < 6 and Stateman > 2, Statesman < 4?

**Comment by mull** [comment]
Like this, right?

**Comment by mull** [comment]
Ping!

**Comment by badosu** [comment]
Thanks for your contribution!

**Comment by mull** [comment]
You're welcome :) Would you mind publishing a new version as well?

**Comment by badosu** [comment]
Done, thank you!

Does this fix #1?

**Comment by mull** [comment]
Yep!

**Comment by badosu** [comment]
Let me know if you find any issues, I am not using sequel-statesman in production anymore, so any feedback is very valuable.

**Pull request merged**
